/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.adminspecific;

import controller.authentication.user.AdminAuthenticator;
import controller.filehandling.AdminFileHandler;
import controller.financial.Balance;
import controller.financial.FinancialFactors;
import controller.management.personnel.PersonnelHandler;
import controller.searching.Searcher;
import model.items.Product;
import model.operations.Operation;
import model.other.Notification;
import model.personnel.Admin;
import model.personnel.Deliverer;
import model.personnel.Pharmacist;
import system.general.DateAndTime;
import view.adders.AddDelivererWindow;
import view.adders.AddPharmacistWindow;
import view.adders.AddToStockMenu;
import view.components.OperationsRenderer;
import view.components.Table;
import view.components.ToastMessage;
import view.general.HomePage;
import view.general.ViewInventory;
import view.optionpanes.CustomOptionPane;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

/**
 * @author Adham Mohamed Aly
 */
public class AdminHome extends javax.swing.JFrame {

    static Thread pharmacistSearcher, delivererSearcher;
    public static final int HOME_TAB = 0, FINANCIAL_TAB = 1, PERSONNEL_TAB = 2, CUSTOMERS_TAB = 3, PHARMACIST_MODE_TAB = 4;

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {

        initComponents();

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        updateOpList();
        setBalanceLabel();

        Table.loadPharmacistTable(pharmacistTable, Pharmacist.pharmacists);
        Table.loadDelivererTable(delivererTable, Deliverer.deliverers);

        dateLabel.setText(DateAndTime.currentDay + " / " + DateAndTime.currentMonth + " / " + DateAndTime.currentYear);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        viewInventoryButton = new javax.swing.JButton();
        addToStockButton = new javax.swing.JButton();
        adminSettingsButton = new javax.swing.JButton();
        cctvButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        Label = new javax.swing.JLabel();
        infoIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notificationArea = new javax.swing.JList<>();
        financialsPanel = new javax.swing.JPanel();
        registerTransactionButton = new javax.swing.JButton();
        chartFinancialsButton = new javax.swing.JButton();
        salesAnalysisButton = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        monthNetProfitLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        opList = new javax.swing.JList<>();
        personnelTabbedPane = new javax.swing.JTabbedPane();
        pharmacistsPanel = new javax.swing.JPanel();
        addPharmacistButton = new javax.swing.JButton();
        managePharmacistButton = new javax.swing.JButton();
        generalPharmacistSettingsButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pharmacistLog = new javax.swing.JTextArea();
        pharmacistSearchBar = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        pharmacistTable = new javax.swing.JTable();
        pharmacistSearchProgress = new javax.swing.JProgressBar();
        label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        deliveryPanel = new javax.swing.JPanel();
        addDelivererButton = new javax.swing.JButton();
        manageDelivererButton = new javax.swing.JButton();
        generalDelivererSettingsButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        delivererLog = new javax.swing.JTextArea();
        delivererSearchBar = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        delivererTable = new javax.swing.JTable();
        delivererSearchProgress = new javax.swing.JProgressBar();
        label1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        managersPanel = new javax.swing.JPanel();
        addManagerButton = new javax.swing.JButton();
        editManagerButton = new javax.swing.JButton();
        editManagerSalariesButton = new javax.swing.JButton();
        removeManagerButton = new javax.swing.JButton();
        addManagerBonusButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        managerLog = new javax.swing.JTextArea();
        viewManagersButton = new javax.swing.JButton();
        customersPanel = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        pharmacistModePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pharmacistModeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Home");

        headerPanel.setBackground(new java.awt.Color(220, 220, 220));
        headerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/logo/default2.png"))); // NOI18N
        logoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoLabelMouseClicked(evt);
            }
        });

        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateLabel.setText("dd / mm / yyyy");

        logOutButton.setText("Logout");
        logOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutButton.setFocusable(false);
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(headerPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(logOutButton)))
                                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(headerPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(logOutButton)))
                                .addContainerGap())
        );

        mainTabbedPane.setBackground(new java.awt.Color(230, 230, 230));
        mainTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainTabbedPane.setFocusable(false);
        mainTabbedPane.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N

        homePanel.setBackground(new java.awt.Color(214, 224, 224));
        homePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                homePanelMouseMoved(evt);
            }
        });

        viewInventoryButton.setBackground(new java.awt.Color(230, 230, 230));
        viewInventoryButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        viewInventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/menuIcons/inventory-icon.png"))); // NOI18N
        viewInventoryButton.setText("View Inventory");
        viewInventoryButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        viewInventoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewInventoryButton.setFocusable(false);
        viewInventoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewInventoryButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewInventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewInventoryButtonMouseEntered(evt);
            }
        });
        viewInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryButtonActionPerformed(evt);
            }
        });

        addToStockButton.setBackground(new java.awt.Color(230, 230, 230));
        addToStockButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        addToStockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/menuIcons/restock-icon.png"))); // NOI18N
        addToStockButton.setText("Add to Stock");
        addToStockButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        addToStockButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addToStockButton.setFocusable(false);
        addToStockButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addToStockButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addToStockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addToStockButtonMouseEntered(evt);
            }
        });
        addToStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToStockButtonActionPerformed(evt);
            }
        });

        adminSettingsButton.setBackground(new java.awt.Color(230, 230, 230));
        adminSettingsButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        adminSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/menuIcons/account-settings-icon.png"))); // NOI18N
        adminSettingsButton.setText("Admin Settings");
        adminSettingsButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        adminSettingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminSettingsButton.setFocusable(false);
        adminSettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminSettingsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        adminSettingsButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                adminSettingsButtonMouseMoved(evt);
            }
        });
        adminSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminSettingsButtonMouseEntered(evt);
            }
        });
        adminSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSettingsButtonActionPerformed(evt);
            }
        });

        cctvButton.setBackground(new java.awt.Color(230, 230, 230));
        cctvButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cctvButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/menuIcons/cctv-icon.png"))); // NOI18N
        cctvButton.setText("CCTV Footage");
        cctvButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        cctvButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cctvButton.setFocusable(false);
        cctvButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cctvButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cctvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cctvButtonActionPerformed(evt);
            }
        });

        notesArea.setColumns(20);
        notesArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        notesArea.setLineWrap(true);
        notesArea.setRows(5);
        notesArea.setText(new AdminFileHandler().loadAdminNotes());
        notesArea.setWrapStyleWord(true);
        notesArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        notesArea.setMargin(new java.awt.Insets(5, 5, 5, 5));
        notesArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                notesAreaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(notesArea);

        Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label.setText("Notes");
        Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        infoIcon.setBackground(new java.awt.Color(153, 153, 153));
        infoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Minimalist_info_Icon.png"))); // NOI18N
        infoIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Notifications");

        notificationArea.setBackground(new java.awt.Color(240, 240, 240));
        notificationArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 88, 84), 3, true));
        notificationArea.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        notificationArea.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(notificationArea);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
                homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(homePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(infoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(homePanelLayout.createSequentialGroup()
                                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(viewInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                                        .addComponent(adminSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cctvButton, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                                        .addComponent(addToStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                                                .addGap(0, 18, Short.MAX_VALUE)
                                                .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(homePanelLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1))
                                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
                homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(homePanelLayout.createSequentialGroup()
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(homePanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                                .addGap(13, 13, 13))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, homePanelLayout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(viewInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cctvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(adminSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(addToStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(infoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        mainTabbedPane.addTab("Home", homePanel);

        financialsPanel.setBackground(new java.awt.Color(214, 224, 224));

        registerTransactionButton.setBackground(new java.awt.Color(230, 230, 230));
        registerTransactionButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        registerTransactionButton.setText("Register Transaction");
        registerTransactionButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        registerTransactionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerTransactionButton.setFocusable(false);
        registerTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerTransactionButtonActionPerformed(evt);
            }
        });

        chartFinancialsButton.setBackground(new java.awt.Color(230, 230, 230));
        chartFinancialsButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chartFinancialsButton.setText("Chart Financials");
        chartFinancialsButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        chartFinancialsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chartFinancialsButton.setFocusable(false);
        chartFinancialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartFinancialsButtonActionPerformed(evt);
            }
        });

        salesAnalysisButton.setBackground(new java.awt.Color(230, 230, 230));
        salesAnalysisButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        salesAnalysisButton.setText("Sales Analysis");
        salesAnalysisButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        salesAnalysisButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salesAnalysisButton.setFocusable(false);
        salesAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesAnalysisButtonActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Label1.setText("Month Net Balance: ");

        monthNetProfitLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        monthNetProfitLabel.setForeground(new java.awt.Color(190, 0, 0));
        monthNetProfitLabel.setText("+$233.7");

        opList.setBackground(new java.awt.Color(234, 234, 234));
        opList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 88, 84), 3, true));
        opList.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        opList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        opList.setCellRenderer(new OperationsRenderer());
        opList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opListMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(opList);

        javax.swing.GroupLayout financialsPanelLayout = new javax.swing.GroupLayout(financialsPanel);
        financialsPanel.setLayout(financialsPanelLayout);
        financialsPanelLayout.setHorizontalGroup(
                financialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(financialsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(financialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane6)
                                        .addGroup(financialsPanelLayout.createSequentialGroup()
                                                .addGroup(financialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(financialsPanelLayout.createSequentialGroup()
                                                                .addComponent(Label1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(monthNetProfitLabel))
                                                        .addGroup(financialsPanelLayout.createSequentialGroup()
                                                                .addComponent(registerTransactionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                                                .addGap(11, 11, 11)))
                                                .addGap(7, 7, 7)
                                                .addComponent(chartFinancialsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(salesAnalysisButton, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        financialsPanelLayout.setVerticalGroup(
                financialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(financialsPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(financialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Label1)
                                        .addComponent(monthNetProfitLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(financialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(registerTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(financialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(salesAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(chartFinancialsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        mainTabbedPane.addTab("Financial", financialsPanel);

        personnelTabbedPane.setBackground(new java.awt.Color(230, 230, 230));
        personnelTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        personnelTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        personnelTabbedPane.setFocusable(false);

        pharmacistsPanel.setBackground(new java.awt.Color(214, 224, 224));

        addPharmacistButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/add-icon-2.png"))); // NOI18N
        addPharmacistButton.setText("New Pharmacist");
        addPharmacistButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addPharmacistButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPharmacistButton.setFocusable(false);
        addPharmacistButton.setMaximumSize(new java.awt.Dimension(135, 41));
        addPharmacistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPharmacistButtonActionPerformed(evt);
            }
        });

        managePharmacistButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/menuIcons/edit-user-icon - small.png"))); // NOI18N
        managePharmacistButton.setText("Manage Pharmacist");
        managePharmacistButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePharmacistButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managePharmacistButton.setFocusable(false);
        managePharmacistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePharmacistButtonActionPerformed(evt);
            }
        });

        generalPharmacistSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/menuIcons/gears-icon-2.png"))); // NOI18N
        generalPharmacistSettingsButton.setText("General Settings");
        generalPharmacistSettingsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generalPharmacistSettingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generalPharmacistSettingsButton.setFocusable(false);
        generalPharmacistSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalPharmacistSettingsButtonActionPerformed(evt);
            }
        });

        pharmacistLog.setEditable(false);
        pharmacistLog.setBackground(javax.swing.UIManager.getDefaults().getColor("TextArea.disabledBackground"));
        pharmacistLog.setColumns(20);
        pharmacistLog.setRows(5);
        pharmacistLog.setText("This log is currently unsupported.\nComing soon though ! :D");
        pharmacistLog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 88, 84), 3, true));
        pharmacistLog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pharmacistLog.setMargin(new java.awt.Insets(6, 6, 6, 6));
        jScrollPane3.setViewportView(pharmacistLog);

        pharmacistSearchBar.setForeground(java.awt.Color.gray);
        pharmacistSearchBar.setText("Search by pharmacist ID or name");
        pharmacistSearchBar.setFocusable(false);
        pharmacistSearchBar.setMargin(new java.awt.Insets(2, 4, 2, 2));
        pharmacistSearchBar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pharmacistSearchBarCaretUpdate(evt);
            }
        });
        pharmacistSearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pharmacistSearchBarFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                pharmacistSearchBarFocusLost(evt);
            }
        });
        pharmacistSearchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pharmacistSearchBarMousePressed(evt);
            }
        });

        pharmacistTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "ID", "Name", "Salary"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        pharmacistTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(pharmacistTable);
        if (pharmacistTable.getColumnModel().getColumnCount() > 0) {
            pharmacistTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            pharmacistTable.getColumnModel().getColumn(0).setMaxWidth(200);
            pharmacistTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            pharmacistTable.getColumnModel().getColumn(2).setMaxWidth(250);
        }

        label.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label.setText("Found: 0 results");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pharmacists");

        javax.swing.GroupLayout pharmacistsPanelLayout = new javax.swing.GroupLayout(pharmacistsPanel);
        pharmacistsPanel.setLayout(pharmacistsPanelLayout);
        pharmacistsPanelLayout.setHorizontalGroup(
                pharmacistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pharmacistsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pharmacistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pharmacistSearchBar)
                                        .addComponent(jScrollPane3)
                                        .addGroup(pharmacistsPanelLayout.createSequentialGroup()
                                                .addComponent(addPharmacistButton, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(managePharmacistButton, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(generalPharmacistSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                                        .addComponent(pharmacistSearchProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pharmacistsPanelLayout.createSequentialGroup()
                                                .addComponent(jSeparator2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1)))
                                .addContainerGap())
        );
        pharmacistsPanelLayout.setVerticalGroup(
                pharmacistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pharmacistsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pharmacistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pharmacistSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pharmacistSearchProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pharmacistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(addPharmacistButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(managePharmacistButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(generalPharmacistSettingsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addContainerGap())
        );

        personnelTabbedPane.addTab("Pharmacists", pharmacistsPanel);

        deliveryPanel.setBackground(new java.awt.Color(214, 224, 224));

        addDelivererButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/add-icon-2.png"))); // NOI18N
        addDelivererButton.setText("New Deliverer");
        addDelivererButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addDelivererButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addDelivererButton.setFocusable(false);
        addDelivererButton.setMaximumSize(new java.awt.Dimension(135, 41));
        addDelivererButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDelivererButtonActionPerformed(evt);
            }
        });

        manageDelivererButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/menuIcons/edit-user-icon - small.png"))); // NOI18N
        manageDelivererButton.setText("Manage Deliverer");
        manageDelivererButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageDelivererButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageDelivererButton.setFocusable(false);
        manageDelivererButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDelivererButtonActionPerformed(evt);
            }
        });

        generalDelivererSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/menuIcons/gears-icon-2.png"))); // NOI18N
        generalDelivererSettingsButton.setText("General Settings");
        generalDelivererSettingsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generalDelivererSettingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generalDelivererSettingsButton.setFocusable(false);
        generalDelivererSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalDelivererSettingsButtonActionPerformed(evt);
            }
        });

        delivererLog.setEditable(false);
        delivererLog.setBackground(javax.swing.UIManager.getDefaults().getColor("TextArea.disabledBackground"));
        delivererLog.setColumns(20);
        delivererLog.setRows(5);
        delivererLog.setText("This log is currently unsupported.\nComing soon though ! :D");
        delivererLog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 88, 84), 3, true));
        delivererLog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        delivererLog.setMargin(new java.awt.Insets(6, 6, 6, 6));
        jScrollPane8.setViewportView(delivererLog);

        delivererSearchBar.setForeground(java.awt.Color.gray);
        delivererSearchBar.setText("Search by deliverer ID or name");
        delivererSearchBar.setFocusable(false);
        delivererSearchBar.setMargin(new java.awt.Insets(2, 4, 2, 2));
        delivererSearchBar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                delivererSearchBarCaretUpdate(evt);
            }
        });
        delivererSearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                delivererSearchBarFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                delivererSearchBarFocusLost(evt);
            }
        });
        delivererSearchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delivererSearchBarMousePressed(evt);
            }
        });

        delivererTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "ID", "Name", "Salary"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        delivererTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(delivererTable);
        if (delivererTable.getColumnModel().getColumnCount() > 0) {
            delivererTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            delivererTable.getColumnModel().getColumn(0).setMaxWidth(200);
            delivererTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            delivererTable.getColumnModel().getColumn(2).setMaxWidth(250);
        }

        label1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label1.setText("Found: 0 results");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Deliverers");

        javax.swing.GroupLayout deliveryPanelLayout = new javax.swing.GroupLayout(deliveryPanel);
        deliveryPanel.setLayout(deliveryPanelLayout);
        deliveryPanelLayout.setHorizontalGroup(
                deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deliveryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(delivererSearchBar)
                                        .addComponent(jScrollPane8)
                                        .addGroup(deliveryPanelLayout.createSequentialGroup()
                                                .addComponent(addDelivererButton, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(manageDelivererButton, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(generalDelivererSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                                        .addComponent(delivererSearchProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryPanelLayout.createSequentialGroup()
                                                .addComponent(jSeparator4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator3)))
                                .addContainerGap())
        );
        deliveryPanelLayout.setVerticalGroup(
                deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deliveryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delivererSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delivererSearchProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(addDelivererButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(manageDelivererButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(generalDelivererSettingsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addContainerGap())
        );

        personnelTabbedPane.addTab("Delivery", deliveryPanel);

        managersPanel.setBackground(new java.awt.Color(214, 224, 224));

        addManagerButton.setBackground(new java.awt.Color(230, 230, 230));
        addManagerButton.setText("Add Manager");
        addManagerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addManagerButton.setFocusable(false);
        addManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManagerButtonActionPerformed(evt);
            }
        });

        editManagerButton.setBackground(new java.awt.Color(230, 230, 230));
        editManagerButton.setText("Edit Manager");
        editManagerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editManagerButton.setFocusable(false);
        editManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editManagerButtonActionPerformed(evt);
            }
        });

        editManagerSalariesButton.setBackground(new java.awt.Color(230, 230, 230));
        editManagerSalariesButton.setText("Edit Salaries");
        editManagerSalariesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editManagerSalariesButton.setFocusable(false);
        editManagerSalariesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editManagerSalariesButtonActionPerformed(evt);
            }
        });

        removeManagerButton.setBackground(new java.awt.Color(230, 230, 230));
        removeManagerButton.setText("Remove Manager");
        removeManagerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeManagerButton.setFocusable(false);
        removeManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeManagerButtonActionPerformed(evt);
            }
        });

        addManagerBonusButton.setBackground(new java.awt.Color(230, 230, 230));
        addManagerBonusButton.setText("Add Bonus");
        addManagerBonusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addManagerBonusButton.setFocusable(false);
        addManagerBonusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManagerBonusButtonActionPerformed(evt);
            }
        });

        managerLog.setEditable(false);
        managerLog.setColumns(20);
        managerLog.setRows(5);
        managerLog.setText("This page is currently unsupported.\nComing soon though ! :D");
        managerLog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(managerLog);

        viewManagersButton.setBackground(new java.awt.Color(230, 230, 230));
        viewManagersButton.setText("View Managers");
        viewManagersButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewManagersButton.setFocusable(false);
        viewManagersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewManagersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout managersPanelLayout = new javax.swing.GroupLayout(managersPanel);
        managersPanel.setLayout(managersPanelLayout);
        managersPanelLayout.setHorizontalGroup(
                managersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(managersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(managersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5)
                                        .addGroup(managersPanelLayout.createSequentialGroup()
                                                .addGroup(managersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                                        .addComponent(viewManagersButton, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(managersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(editManagerSalariesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                                        .addComponent(editManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(managersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(removeManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                                        .addComponent(addManagerBonusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        managersPanelLayout.setVerticalGroup(
                managersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(managersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(managersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addManagerButton)
                                        .addComponent(editManagerButton)
                                        .addComponent(removeManagerButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(managersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addManagerBonusButton)
                                        .addComponent(editManagerSalariesButton)
                                        .addComponent(viewManagersButton))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                                .addContainerGap())
        );

        personnelTabbedPane.addTab("Managers", managersPanel);

        mainTabbedPane.addTab("Personnel", personnelTabbedPane);

        jLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("This menu is currently under development!");

        javax.swing.GroupLayout customersPanelLayout = new javax.swing.GroupLayout(customersPanel);
        customersPanel.setLayout(customersPanelLayout);
        customersPanelLayout.setHorizontalGroup(
                customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(customersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                                .addContainerGap())
        );
        customersPanelLayout.setVerticalGroup(
                customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(customersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                                .addContainerGap())
        );

        mainTabbedPane.addTab("Customers", customersPanel);

        pharmacistModePanel.setBackground(new java.awt.Color(214, 224, 224));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 29)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Pharmacist Mode");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel2.setText("This mode allows the admin to perform pharmacist actions such as selling items.");

        jPanel2.setBackground(new java.awt.Color(193, 206, 203));

        jLabel3.setBackground(new java.awt.Color(194, 204, 204));
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(193, 206, 203));

        jLabel4.setBackground(new java.awt.Color(194, 204, 204));
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(194, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(194, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(194, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        pharmacistModeButton.setBackground(new java.awt.Color(50, 101, 101));
        pharmacistModeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/activate-icon.png"))); // NOI18N
        pharmacistModeButton.setText("Switch to pharmacist mode");
        pharmacistModeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pharmacistModeButton.setFocusable(false);
        pharmacistModeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pharmacistModeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pharmacistModeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pharmacistModeButtonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                pharmacistModeButtonMouseExited(evt);
            }
        });
        pharmacistModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacistModeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pharmacistModeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pharmacistModeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout pharmacistModePanelLayout = new javax.swing.GroupLayout(pharmacistModePanel);
        pharmacistModePanel.setLayout(pharmacistModePanelLayout);
        pharmacistModePanelLayout.setHorizontalGroup(
                pharmacistModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pharmacistModePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pharmacistModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pharmacistModePanelLayout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(pharmacistModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE))
                                .addContainerGap())
        );
        pharmacistModePanelLayout.setVerticalGroup(
                pharmacistModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pharmacistModePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(pharmacistModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pharmacistModePanelLayout.createSequentialGroup()
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        mainTabbedPane.addTab("Pharmacist Mode", pharmacistModePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainTabbedPane))
        );

        mainTabbedPane.getAccessibleContext().setAccessibleName("Home\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Updates the completed operations lists in the 'Financial' tab
     * @author Adham Mohamed Aly
     */
    private void updateOpList() {
        DefaultListModel<Operation> listModel = new DefaultListModel<>();
        for (int opID : Operation.completedOperations.keySet()) {
            listModel.addElement(Operation.completedOperations.get(opID));
        }
        opList.setModel(listModel);
    }

    /**
     * Set the value of the 'Month Net Balance' label
     * @author Adham Mohamed Aly
     */
    private void setBalanceLabel() {
        Balance.adjustMonthBalance();
        if (Balance.monthNetBalance > 0) {
            monthNetProfitLabel.setForeground(new java.awt.Color(0, 125, 0));
            monthNetProfitLabel.setText("+" + FinancialFactors.PREFERRED_CURRENCY + String.format("%.2f", Balance.monthNetBalance));
        } else if (Balance.monthNetBalance < 0) {
            monthNetProfitLabel.setForeground(new java.awt.Color(190, 0, 0));
            monthNetProfitLabel.setText("-" + FinancialFactors.PREFERRED_CURRENCY + String.format("%.2f", Math.abs(Balance.monthNetBalance)));
        } else {
            monthNetProfitLabel.setForeground(new java.awt.Color(120, 120, 120));
            monthNetProfitLabel.setText("+" + FinancialFactors.PREFERRED_CURRENCY + "0.00");
        }
    }

    private void adminSettingsButtonMouseMoved(MouseEvent evt) {
    }

    private void accountSettingsButtonMouseMoved(MouseEvent evt) {
    }

    private void homePanelMouseMoved(MouseEvent evt) {
    }

    private void editManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editManagerButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_editManagerButtonActionPerformed

    private void editManagerSalariesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editManagerSalariesButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_editManagerSalariesButtonActionPerformed

    private void addManagerBonusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManagerBonusButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_addManagerBonusButtonActionPerformed

    private void logoLabelMouseClicked(java.awt.event.MouseEvent evt) {
        //
    }

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        int choice = CustomOptionPane.showLogoutDialog();

        if (choice == 1) {
            this.dispose();
            new HomePage().setVisible(true);
        }
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void viewInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryButtonActionPerformed
        ViewInventory.previousMenu = ViewInventory.ADMIN_MENU;
        new ViewInventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewInventoryButtonActionPerformed

    private void addToStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToStockButtonActionPerformed
        this.dispose();
        AddToStockMenu.previousMenu = AddToStockMenu.ADMIN_MENU;
        new AddToStockMenu().setVisible(true);
    }//GEN-LAST:event_addToStockButtonActionPerformed

    private void adminSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSettingsButtonActionPerformed
        new AdminSettings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminSettingsButtonActionPerformed

    private void cctvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cctvButtonActionPerformed
        CustomOptionPane.showMessageDialog("No CCTV equipment connected.");
    }//GEN-LAST:event_cctvButtonActionPerformed

    private void addPharmacistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPharmacistButtonActionPerformed
        new AddPharmacistWindow(pharmacistTable).setVisible(true);
        pharmacistSearchBar.transferFocus();
        pharmacistSearchBar.setText("");
        resetPharmacistSearchBar();
    }//GEN-LAST:event_addPharmacistButtonActionPerformed


    private void adminSettingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSettingsButtonMouseEntered
        if (AdminAuthenticator.useDefault) {
            ToastMessage toast = new ToastMessage("You're currently using default admin credentials. Changing the username and password is recommended",
                    true, getX() + 55, getY() + getHeight() - 55);

            toast.showToast();
        }
    }//GEN-LAST:event_adminSettingsButtonMouseEntered

    private void registerTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerTransactionButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_registerTransactionButtonActionPerformed

    private void chartFinancialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartFinancialsButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_chartFinancialsButtonActionPerformed

    private void salesAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesAnalysisButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_salesAnalysisButtonActionPerformed

    private void managePharmacistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePharmacistButtonActionPerformed
        int selectedItem = pharmacistTable.getSelectedRow();
        if (selectedItem == -1) {
            ToastMessage toast = new ToastMessage("Please choose a pharmacist to manage",
                    false, getX() + (getWidth() / 2 - 80), getY() + getHeight() - 90);

            toast.showToast();
        } else {
            ManagePharmacistFrame.displayedPharmacist = Pharmacist.pharmacists.get(
                    Integer.parseInt((String) pharmacistTable.getValueAt(selectedItem, 0)) - PersonnelHandler.PHARMACIST_BASE_ID);
            new ManagePharmacistFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_managePharmacistButtonActionPerformed

    private void generalPharmacistSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalPharmacistSettingsButtonActionPerformed
        AdminSettings adminSettings = new AdminSettings();
        AdminSettings.previousIndex = mainTabbedPane.getSelectedIndex();
        adminSettings.navigateToPersonnelSettings(AdminSettings.PERSONNEL_PHARMACIST_TAB);
        adminSettings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generalPharmacistSettingsButtonActionPerformed

    private void addManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManagerButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_addManagerButtonActionPerformed

    private void removeManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeManagerButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_removeManagerButtonActionPerformed

    private void viewManagersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewManagersButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_viewManagersButtonActionPerformed

    private void pharmacistModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacistModeButtonActionPerformed
        Admin.activateAdminPharmacist();
        new PharmacistLoadingFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pharmacistModeButtonActionPerformed

    private void viewInventoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInventoryButtonMouseEntered
        int count = 0;
        for (int id : Product.productInventory.keySet()) {
            if (Product.productInventory.get(id).getQuantityInStock() == 0) {
                count++;
            }
        }
        if ((count == 1)) {
            ToastMessage toast = new ToastMessage("Warning: 1 registered item is out of stock.",
                    true, getX() + 55, getY() + getHeight() - 55);

            toast.showToast();
        } else if (count > 0) {
            ToastMessage toast = new ToastMessage("Warning: " + count + " registered items are out of stock.",
                    true, getX() + 55, getY() + getHeight() - 55);

            toast.showToast();
        }
    }//GEN-LAST:event_viewInventoryButtonMouseEntered

    private void addToStockButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToStockButtonMouseEntered
        viewInventoryButtonMouseEntered(evt);
    }//GEN-LAST:event_addToStockButtonMouseEntered

    private void opListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opListMouseClicked
        Operation selection = opList.getSelectedValue();
        opList.clearSelection();
        if (selection != null) {
            OperationDetailsFrame.displayedOp = selection;
        }
        new OperationDetailsFrame().setVisible(true);
    }//GEN-LAST:event_opListMouseClicked

    private void pharmacistModeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacistModeButtonMouseEntered
        pharmacistModeButton.setForeground(Color.white);
        pharmacistModeButton.setIcon(new ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/activate-icon-2.png")));
        jPanel6.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_pharmacistModeButtonMouseEntered

    private void pharmacistModeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacistModeButtonMouseExited
        pharmacistModeButton.setForeground(Color.black);
        pharmacistModeButton.setIcon(new ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/activate-icon.png")));
        jPanel6.setBackground(new Color(163, 173, 173));
    }//GEN-LAST:event_pharmacistModeButtonMouseExited

    private void notesAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notesAreaKeyReleased
        String notes = notesArea.getText();
        new AdminFileHandler().saveAdminNotes(notes);
    }//GEN-LAST:event_notesAreaKeyReleased

    private void pharmacistSearchBarFocusLost(java.awt.event.FocusEvent evt) {
        resetPharmacistSearchBar();
    }

    /**
     * Resets the pharmacist search bar to the standard format
     * @author Adham Mohamed Aly
     */
    private void resetPharmacistSearchBar() {
        pharmacistSearchBar.setFocusable(false);
        if (pharmacistSearchBar.getText().trim().isEmpty()) {
            pharmacistSearchBar.setForeground(Color.GRAY);
            pharmacistSearchBar.setText("Search by pharmacist ID or name");
        }
    }

    private void pharmacistSearchBarFocusGained(java.awt.event.FocusEvent evt) {
        pharmacistSearchBar.setForeground(Color.black);
        pharmacistSearchBar.setText("");
    }

    private void pharmacistSearchBarMousePressed(java.awt.event.MouseEvent evt) {
        pharmacistSearchBar.setFocusable(true);
        pharmacistSearchBar.grabFocus();
    }

    private void pharmacistSearchBarCaretUpdate(javax.swing.event.CaretEvent evt) {
        if (pharmacistSearcher != null && pharmacistSearcher.isAlive()) {
            pharmacistSearcher.stop();
        }
        pharmacistSearcher = new Thread(this::getPharmacistSearchResults);
        pharmacistSearcher.start();
    }

    private void addDelivererButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDelivererButtonActionPerformed
        new AddDelivererWindow(delivererTable).setVisible(true);
        delivererSearchBar.transferFocus();
        delivererSearchBar.setText("");
        resetDelivererSearchBar();
    }//GEN-LAST:event_addDelivererButtonActionPerformed

    private void manageDelivererButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDelivererButtonActionPerformed
        int selectedItem = delivererTable.getSelectedRow();
        if (selectedItem == -1) {
            ToastMessage toast = new ToastMessage("Please choose a deliverer to manage",
                    false, getX() + (getWidth() / 2 - 80), getY() + getHeight() - 90);

            toast.showToast();
        } else {
            ManageDelivererFrame.displayedDeliverer
                    = Deliverer.deliverers.get(
                    Integer.parseInt((String) delivererTable.getValueAt(selectedItem, 0)) - PersonnelHandler.DELIVERER_BASE_ID);
            this.dispose();
            new ManageDelivererFrame().setVisible(true);
        }
    }//GEN-LAST:event_manageDelivererButtonActionPerformed

    private void generalDelivererSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalDelivererSettingsButtonActionPerformed
        AdminSettings adminSettings = new AdminSettings();
        AdminSettings.previousIndex = mainTabbedPane.getSelectedIndex();
        adminSettings.navigateToPersonnelSettings(AdminSettings.PERSONNEL_DELIVERER_TAB);
        adminSettings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generalDelivererSettingsButtonActionPerformed

    private void delivererSearchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pharmacistSearchBarFocusLost
        resetDelivererSearchBar();
    }//GEN-LAST:event_pharmacistSearchBarFocusLost

    /**
     * Resets the deliverer search bar to the standard format
     * @author Adham Mohamed Aly
     */
    private void resetDelivererSearchBar() {
        delivererSearchBar.setFocusable(false);
        if (delivererSearchBar.getText().trim().isEmpty()) {
            delivererSearchBar.setForeground(Color.GRAY);
            delivererSearchBar.setText("Search by deliverer ID or name");
        }
    }

    private void delivererSearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pharmacistSearchBarFocusGained
        delivererSearchBar.setForeground(Color.black);
        delivererSearchBar.setText("");
    }//GEN-LAST:event_pharmacistSearchBarFocusGained

    private void delivererSearchBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacistSearchBarMousePressed
        delivererSearchBar.setFocusable(true);
        delivererSearchBar.grabFocus();
    }//GEN-LAST:event_pharmacistSearchBarMousePressed

    private void delivererSearchBarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pharmacistSearchBarCaretUpdate
        if (delivererSearcher != null && delivererSearcher.isAlive()) {
            delivererSearcher.stop();
        }
        delivererSearcher = new Thread(this::getDelivererSearchResults);
        delivererSearcher.start();
    }//GEN-LAST:event_pharmacistSearchBarCaretUpdate

    /**
     * Search for deliverers related to the input entered in the search bar and display the
     * results in the deliverer table.
     * @author Adham Mohamed Aly
     */
    private void getDelivererSearchResults() {
        int inputID = 0;
        ArrayList<Deliverer> results;
        if (delivererSearchBar.getText().trim().isEmpty() || delivererSearchBar.getForeground() == Color.GRAY) {
            delivererSearchProgress.setValue(0);
            label1.setText("Found: 0 results");
            Table.loadDelivererTable(delivererTable, Deliverer.deliverers);
        } else {
            try {
                inputID = Integer.parseInt(delivererSearchBar.getText().trim());
                results = new Searcher().getDelivererSearchResults(inputID, delivererSearchProgress, label1);
            } catch (NumberFormatException e) {
                results = new Searcher().getDelivererSearchResults(delivererSearchBar.getText().trim(), delivererSearchProgress, label1);
            }
            if (results != null) {
                Table.loadDelivererTable(delivererTable, results);
            }
        }
    }

    /**
     * Search for pharmacists related to the input entered in the search bar and display the
     * results in the pharmacists table.
     * @author Adham Mohamed Aly
     */
    private synchronized void getPharmacistSearchResults() {
        int inputID = 0;
        ArrayList<Pharmacist> results;

        if (pharmacistSearchBar.getText().trim().isEmpty() || pharmacistSearchBar.getForeground() == Color.GRAY) {
            pharmacistSearchProgress.setValue(0);
            label.setText("Found: 0 results");
            Table.loadPharmacistTable(pharmacistTable, Pharmacist.pharmacists);
        } else {
            try {
                inputID = Integer.parseInt(pharmacistSearchBar.getText().trim());
                results = new Searcher().getPharmacistSearchResults(inputID, pharmacistSearchProgress, label);
            } catch (NumberFormatException e) {
                results = new Searcher().getPharmacistSearchResults(pharmacistSearchBar.getText().trim(), pharmacistSearchProgress, label);
            }
            if (results != null) {
                Table.loadPharmacistTable(pharmacistTable, results);
            }
        }
    }

    /**
     * Navigates to the given tab. Tab indexing is zero based
     * @implNote 1. It is recommended to use the enumerated values in the {@code AdminHome} class
     * <p>
     *     2. It is better to invoke this method before setting the frame to be visible in order for it to work optimally
     * </p>
     * @param tabIndex The index of the tab you wish to navigate to
     */
    public void navigateTo(int tabIndex) throws IndexOutOfBoundsException {
        mainTabbedPane.setSelectedIndex(tabIndex);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JLabel Label1;
    private javax.swing.JButton addDelivererButton;
    private javax.swing.JButton addManagerBonusButton;
    private javax.swing.JButton addManagerButton;
    private javax.swing.JButton addPharmacistButton;
    private javax.swing.JButton addToStockButton;
    private javax.swing.JButton adminSettingsButton;
    private javax.swing.JButton cctvButton;
    private javax.swing.JButton chartFinancialsButton;
    private javax.swing.JPanel customersPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextArea delivererLog;
    private javax.swing.JTextField delivererSearchBar;
    private javax.swing.JProgressBar delivererSearchProgress;
    private javax.swing.JTable delivererTable;
    private javax.swing.JPanel deliveryPanel;
    private javax.swing.JButton editManagerButton;
    private javax.swing.JButton editManagerSalariesButton;
    private javax.swing.JPanel financialsPanel;
    private javax.swing.JButton generalDelivererSettingsButton;
    private javax.swing.JButton generalPharmacistSettingsButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel infoIcon;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton manageDelivererButton;
    private javax.swing.JButton managePharmacistButton;
    private javax.swing.JTextArea managerLog;
    private javax.swing.JPanel managersPanel;
    private javax.swing.JLabel monthNetProfitLabel;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JList<Notification> notificationArea;
    private javax.swing.JList<Operation> opList;
    private javax.swing.JTabbedPane personnelTabbedPane;
    private javax.swing.JTextArea pharmacistLog;
    private javax.swing.JButton pharmacistModeButton;
    private javax.swing.JPanel pharmacistModePanel;
    private javax.swing.JTextField pharmacistSearchBar;
    private javax.swing.JProgressBar pharmacistSearchProgress;
    private javax.swing.JTable pharmacistTable;
    private javax.swing.JPanel pharmacistsPanel;
    private javax.swing.JButton registerTransactionButton;
    private javax.swing.JButton removeManagerButton;
    private javax.swing.JButton salesAnalysisButton;
    private javax.swing.JButton viewInventoryButton;
    private javax.swing.JButton viewManagersButton;
    // End of variables declaration//GEN-END:variables
}
