/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.adminspecific;

import controller.authentication.user.AdminAuthenticator;
import controller.filehandling.AdminFileHandler;
import controller.financial.FinancialFactors;
import controller.management.personnel.AdminHandler;
import model.personnel.Admin;
import system.general.DateAndTime;
import view.optionpanes.CustomOptionPane;

import javax.swing.*;
import java.awt.*;
import java.util.Vector;

/**
 * @author drogo
 */
public class AdminSettings extends javax.swing.JFrame {

    public static int previousIndex = 0;

    static boolean passwordIsHidden;
    static Vector<Boolean> changes = new Vector<>();

    String hiddenPassword = "";

    static SpinnerNumberModel taxSpinnerNumberModel = new SpinnerNumberModel();
    static SpinnerNumberModel deliveryFeesSpinnerNumberModel = new SpinnerNumberModel();
    private boolean changingPassword;
    private boolean changingUsername;

    public static final int PERSONNEL_GENERAL_TAB = 0, PERSONNEL_PHARMACIST_TAB = 1, PERSONNEL_DELIVERER_TAB = 2;

    /**
     * Creates new form AdminAccountSettings
     */
    public AdminSettings() {
        for (int i = 0; i < Admin.currentAdmin.getPassword().length(); i++) {
            hiddenPassword += "*";
        }

        initComponents();
        customInitComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        dateLabel.setText(DateAndTime.currentDay + " / " + DateAndTime.currentMonth + " / " + DateAndTime.currentYear);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();
        adminInfoPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        changeUsernameButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();
        resetLoginCredentialsButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dayComboBox1 = new javax.swing.JComboBox<>();
        monthComboBox1 = new javax.swing.JComboBox<>();
        yearComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cancelButton3 = new javax.swing.JButton();
        cancelButton4 = new javax.swing.JButton();
        financialPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        taxSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editTaxesButton = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deliveryFeesSpinner = new javax.swing.JSpinner();
        cancelButton2 = new javax.swing.JButton();
        editDeliveryFeesButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        currencyComboBox = new javax.swing.JComboBox<>();
        convertPricesButton = new javax.swing.JButton();
        promptLabel1 = new javax.swing.JLabel();
        promptLabel2 = new javax.swing.JLabel();
        personnelPane = new javax.swing.JTabbedPane();
        generalTab = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        pharmacistsTab = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        deliverersTab = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Settings");

        headerPanel.setBackground(new java.awt.Color(220, 220, 220));
        headerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/logo/default2.png"))); // NOI18N
        logoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoLabelMouseClicked(evt);
            }
        });

        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateLabel.setText("dd / mm / yyyy");

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(doneButton)))
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addComponent(doneButton)))
                .addContainerGap())
        );

        mainTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        mainTabbedPane.setFocusable(false);

        adminInfoPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Here you can view / modify your login credentials (username & password)");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel7.setText("Login Credentials");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Password");

        usernameField.setEditable(false);
        usernameField.setText(Admin.currentAdmin.getUserName());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/hide-icon.png"))); // NOI18N
        jLabel9.setText("Show");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        passwordField.setEditable(false);
        passwordField.setText(hiddenPassword);
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });

        changeUsernameButton.setText("Change username");
        changeUsernameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeUsernameButton.setFocusable(false);
        changeUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernameButtonActionPerformed(evt);
            }
        });

        changePasswordButton.setText("Change password");
        changePasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePasswordButton.setFocusable(false);
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        resetLoginCredentialsButton.setText("Reset to defaults");
        resetLoginCredentialsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resetLoginCredentialsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetLoginCredentialsButton.setFocusable(false);
        resetLoginCredentialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetLoginCredentialsButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("Username");

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel11.setText("Basic Info");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("Here you can view / modify basic info such as name, date of birth, etc..");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setText("Don't forget to save your changes !");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setText("Name");

        nameField.setEditable(false);
        nameField.setText(Admin.currentAdmin.getName());

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setText("Date of Birth");

        dayComboBox1.setMaximumRowCount(31);
        dayComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        monthComboBox1.setMaximumRowCount(12);
        monthComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        yearComboBox1.setMaximumRowCount(121);
        yearComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        yearComboBox1.setSelectedIndex(90);

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setText("Don't forget to save your changes !");

        cancelButton3.setBackground(new java.awt.Color(255, 51, 51));
        cancelButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Very-Basic-Cancel-icon.png"))); // NOI18N
        cancelButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton3.setFocusable(false);
        cancelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton3ActionPerformed(evt);
            }
        });

        cancelButton4.setBackground(new java.awt.Color(255, 51, 51));
        cancelButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Very-Basic-Cancel-icon.png"))); // NOI18N
        cancelButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton4.setFocusable(false);
        cancelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetLoginCredentialsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dayComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yearComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changePasswordButton)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changeUsernameButton)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(714, 714, 714))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeUsernameButton)
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changePasswordButton))
                    .addComponent(cancelButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(resetLoginCredentialsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        adminInfoPane.setViewportView(jPanel2);

        mainTabbedPane.addTab("Admin Info", adminInfoPane);

        financialPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel17.setText("Additional Fees");

        jSeparator3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Here you can view / modify additional fees applied on client purchases (taxes, delivery fees, etc.)");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setText("Taxes");

        taxSpinner.setModel(new javax.swing.SpinnerNumberModel(14.0d, 0.0d, null, 1.0d));
        taxSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taxSpinner.setEnabled(false);
        taxSpinner.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText(String.valueOf(FinancialFactors.PREFERRED_CURRENCY));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("%");

        editTaxesButton.setText("Edit taxes");
        editTaxesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editTaxesButton.setFocusable(false);
        editTaxesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaxesButtonActionPerformed(evt);
            }
        });

        cancelButton1.setBackground(new java.awt.Color(255, 51, 51));
        cancelButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Very-Basic-Cancel-icon.png"))); // NOI18N
        cancelButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton1.setFocusable(false);
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setText("Base Delivery Fees");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText(String.valueOf(FinancialFactors.PREFERRED_CURRENCY));

        deliveryFeesSpinner.setModel(new javax.swing.SpinnerNumberModel(4.99d, 0.0d, null, 1.0d));
        deliveryFeesSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliveryFeesSpinner.setEnabled(false);
        deliveryFeesSpinner.setFocusable(false);

        cancelButton2.setBackground(new java.awt.Color(255, 51, 51));
        cancelButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Very-Basic-Cancel-icon.png"))); // NOI18N
        cancelButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton2.setFocusable(false);
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });

        editDeliveryFeesButton.setText("Edit Delivery Fees");
        editDeliveryFeesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editDeliveryFeesButton.setFocusable(false);
        editDeliveryFeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDeliveryFeesButtonActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel20.setText("Pricing & Currency");

        jSeparator4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Here you can view / modify pricing settings in your system. These changes consist of value");

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("and format-related modifications concerning prices of items you sell.");

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setText("Preferred Currency");

        currencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dollar", "Egyptian Pound", "Euro", "Sterling" }));
        currencyComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        currencyComboBox.setFocusable(false);
        currencyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyComboBoxActionPerformed(evt);
            }
        });
        currencyComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                currencyComboBoxPropertyChange(evt);
            }
        });

        convertPricesButton.setText("Convert price values");
        convertPricesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convertPricesButton.setFocusable(false);
        convertPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertPricesButtonActionPerformed(evt);
            }
        });

        promptLabel1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        promptLabel1.setForeground(new java.awt.Color(120, 120, 120));
        promptLabel1.setText("*Your changes will be applied when you press done");
        promptLabel1.setFocusable(false);

        promptLabel2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        promptLabel2.setForeground(new java.awt.Color(120, 120, 120));
        promptLabel2.setText("*Commission values and in depth delivery fee settings can be configured in Personnel > Deliverers");
        promptLabel2.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editDeliveryFeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editTaxesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taxSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deliveryFeesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(currencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(convertPricesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(promptLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(promptLabel2)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(taxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTaxesButton)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel5)
                        .addComponent(deliveryFeesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editDeliveryFeesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptLabel2)
                .addGap(55, 55, 55)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(currencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(convertPricesButton)
                        .addComponent(promptLabel1))
                    .addComponent(jLabel22))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        financialPane.setViewportView(jPanel1);

        mainTabbedPane.addTab("Financial", financialPane);

        personnelPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel23.setText("Personnel General Settings");

        jSeparator5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout generalTabLayout = new javax.swing.GroupLayout(generalTab);
        generalTab.setLayout(generalTabLayout);
        generalTabLayout.setHorizontalGroup(
            generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        generalTabLayout.setVerticalGroup(
            generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        personnelPane.addTab("General", generalTab);

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel24.setText("Pharmacist Settings");

        jSeparator6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout pharmacistsTabLayout = new javax.swing.GroupLayout(pharmacistsTab);
        pharmacistsTab.setLayout(pharmacistsTabLayout);
        pharmacistsTabLayout.setHorizontalGroup(
            pharmacistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pharmacistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pharmacistsTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pharmacistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pharmacistsTabLayout.setVerticalGroup(
            pharmacistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pharmacistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pharmacistsTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel24)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        personnelPane.addTab("Pharmacists", pharmacistsTab);

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel25.setText("Deliverer Settings");

        jSeparator7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout deliverersTabLayout = new javax.swing.GroupLayout(deliverersTab);
        deliverersTab.setLayout(deliverersTabLayout);
        deliverersTabLayout.setHorizontalGroup(
            deliverersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(deliverersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deliverersTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(deliverersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        deliverersTabLayout.setVerticalGroup(
            deliverersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(deliverersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deliverersTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel25)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        personnelPane.addTab("Deilverers", deliverersTab);

        mainTabbedPane.addTab("Personnel", personnelPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customInitComponents() {
        taxSpinnerNumberModel.setValue(FinancialFactors.TAX_FACTOR * 100);
        taxSpinnerNumberModel.setMinimum(0.0);
        taxSpinnerNumberModel.setStepSize(0.5);
        taxSpinner.setModel(taxSpinnerNumberModel);

        deliveryFeesSpinnerNumberModel.setValue(FinancialFactors.DELIVERY_FEE);
        deliveryFeesSpinnerNumberModel.setMinimum(0.0);
        deliveryFeesSpinnerNumberModel.setStepSize(1);
        deliveryFeesSpinner.setModel(deliveryFeesSpinnerNumberModel);

        cancelButton1.setVisible(false);
        cancelButton2.setVisible(false);
        cancelButton3.setVisible(false);
        cancelButton4.setVisible(false);

        if (FinancialFactors.PREFERRED_CURRENCY.equals(FinancialFactors.US_DOLLAR)) {
            currencyComboBox.setSelectedIndex(FinancialFactors.USD);
        } else if (FinancialFactors.PREFERRED_CURRENCY.equals(FinancialFactors.EGYPTIAN_POUND)) {
            currencyComboBox.setSelectedIndex(FinancialFactors.EGP);
        } else if (FinancialFactors.PREFERRED_CURRENCY.equals(FinancialFactors.EURO)) {
            currencyComboBox.setSelectedIndex(FinancialFactors.EUR);
        } else if (FinancialFactors.PREFERRED_CURRENCY.equals(FinancialFactors.STERLING_POUND)) {
            currencyComboBox.setSelectedIndex(FinancialFactors.STERLING);
        }
    }

    private void logoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoLabelMouseClicked

    void changePasswordFieldView() {
        if (passwordIsHidden) {
            jLabel9.setText("Show");
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/hide-icon.png")));

            String password = "";
            for (int i = 0; i < Admin.currentAdmin.getPassword().length(); i++) {
                password += "*";
            }
            passwordField.setText(password);

            passwordIsHidden = false;
        } else {
            jLabel9.setText("Hide");
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/eye-icon.png")));
            passwordField.setText(Admin.currentAdmin.getPassword());
            passwordIsHidden = true;
        }
    }

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        int choice = 0;
        if (!changes.isEmpty()) {
            choice = JOptionPane.showConfirmDialog(
                    null, "You have unfinished changes. Exit anyway?", "", JOptionPane.YES_NO_OPTION);
        }
        if (choice == 0) {
            this.dispose();
            AdminHome adminHome = new AdminHome();
            adminHome.navigateTo(previousIndex);
            previousIndex = 0;
            adminHome.setVisible(true);
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void resetLoginCredentialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetLoginCredentialsButtonActionPerformed

        if (JOptionPane.showConfirmDialog(null, "Reset login credentials to default values?", "", JOptionPane.YES_NO_OPTION) == 0) {

            AdminAuthenticator.useDefault = true;
            AdminHandler.setDefaultLoginCredentials();

            new AdminFileHandler().saveToFile();

            usernameField.setText(Admin.currentAdmin.getUserName());
            passwordField.setText(Admin.currentAdmin.getPassword());
            changePasswordFieldView();

        }
    }//GEN-LAST:event_resetLoginCredentialsButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        if (!changingPassword) {
            changePasswordButton.setText("Save");
            cancelButton4.setVisible(true);

            passwordField.setText(Admin.currentAdmin.getPassword());
            passwordField.setEditable(true);

            jLabel9.setVisible(false);

            changingPassword = true;
            changes.add(true);
        } else {
            String temp = passwordField.getText();

            if (!temp.equals(Admin.currentAdmin.getPassword())) {
                String confirm = CustomOptionPane.showPasswordDialog();

                if (confirm != null && confirm.equals(temp)) {
                    Admin.currentAdmin.setPassword(temp);
                    AdminAuthenticator.useDefault = Admin.currentAdmin.getUserName().equalsIgnoreCase(AdminAuthenticator.defaultAdminUsername) && Admin.currentAdmin.getPassword().equals(AdminAuthenticator.defaultAdminPassword);
                    new AdminFileHandler().saveToFile();
                    CustomOptionPane.showMessageDialog("Admin password has been changed successfully", "Success");
                }
            }

            jLabel9.setVisible(true);
            cancelButton4.setVisible(false);
            changePasswordButton.setText("Change Password");

            passwordField.setText(Admin.currentAdmin.getPassword());
            passwordField.setEditable(false);
            changePasswordFieldView();

            changingPassword = false;
            changes.remove(changes.size() - 1);
        }
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void changeUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernameButtonActionPerformed
        if (!changingUsername) {
            changeUsernameButton.setText("Save");
            cancelButton3.setVisible(true);

            usernameField.setEditable(true);

            changingUsername = true;
            changes.add(true);
        } else {
            String temp = usernameField.getText();

            if (!temp.equals(Admin.currentAdmin.getUserName())) {
                int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you wish to change the admin username?\n\n\"" + Admin.currentAdmin.getUserName() + "\" => \"" + temp + "\"", "Are you sure?", JOptionPane.YES_NO_OPTION);

                if (confirm == 0) {
                    Admin.currentAdmin.setUserName(temp);
                    AdminAuthenticator.useDefault = Admin.currentAdmin.getUserName().equalsIgnoreCase(AdminAuthenticator.defaultAdminUsername) && Admin.currentAdmin.getPassword().equals(AdminAuthenticator.defaultAdminPassword);
                    new AdminFileHandler().saveToFile();
                    CustomOptionPane.showMessageDialog("Admin username has been changed successfully", "Success");
                }
            }

            changeUsernameButton.setText("Change Username");

            cancelButton3.setVisible(false);

            usernameField.setText(Admin.currentAdmin.getUserName());
            usernameField.setEditable(false);

            changingUsername = false;
            changes.remove(changes.size() - 1);
        }
    }//GEN-LAST:event_changeUsernameButtonActionPerformed

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        changePasswordFieldView();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void editTaxesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaxesButtonActionPerformed
        if (!taxSpinner.isEnabled()) {
            taxSpinner.setEnabled(true);
            editTaxesButton.setText("Set tax");
            cancelButton1.setVisible(true);
            changes.add(true);
        } else {
            FinancialFactors.TAX_FACTOR = (Double) taxSpinner.getValue() / 100;
            taxSpinner.setEnabled(false);
            editTaxesButton.setText("Edit taxes");
            cancelButton1.setVisible(false);
            changes.remove(changes.size() - 1);
        }
    }//GEN-LAST:event_editTaxesButtonActionPerformed

    private void editDeliveryFeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDeliveryFeesButtonActionPerformed
        if (!deliveryFeesSpinner.isEnabled()) {
            deliveryFeesSpinner.setEnabled(true);
            editDeliveryFeesButton.setText("Set delivery fee");
            cancelButton2.setVisible(true);
            changes.add(true);
        } else {
            FinancialFactors.DELIVERY_FEE = (Double) deliveryFeesSpinner.getValue();
            deliveryFeesSpinner.setEnabled(false);
            editDeliveryFeesButton.setText("Edit delivery fee");
            cancelButton2.setVisible(false);
            changes.remove(changes.size() - 1);
        }
    }//GEN-LAST:event_editDeliveryFeesButtonActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        taxSpinner.setEnabled(false);
        editTaxesButton.setText("Edit taxes");
        cancelButton1.setVisible(false);
        taxSpinner.setValue(FinancialFactors.TAX_FACTOR * 100);
        changes.remove(changes.size() - 1);
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton2ActionPerformed
        deliveryFeesSpinner.setEnabled(false);
        editDeliveryFeesButton.setText("Edit delivery fee");
        cancelButton2.setVisible(false);
        deliveryFeesSpinner.setValue(FinancialFactors.DELIVERY_FEE);
        changes.remove(changes.size() - 1);
    }//GEN-LAST:event_cancelButton2ActionPerformed

    private void cancelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton3ActionPerformed
        usernameField.setEditable(false);
        usernameField.transferFocus();
        changeUsernameButton.setText("Change Username");
        cancelButton3.setVisible(false);
        usernameField.setText(Admin.currentAdmin.getUserName());
        changingUsername = false;
        changes.remove(changes.size() - 1);
    }//GEN-LAST:event_cancelButton3ActionPerformed

    private void cancelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton4ActionPerformed
        passwordField.setEditable(false);
        passwordField.transferFocus();
        changePasswordButton.setText("Change password");
        cancelButton4.setVisible(false);
        jLabel9.setVisible(true);
        changePasswordFieldView();
        changingPassword = false;
        changes.remove(changes.size() - 1);
    }//GEN-LAST:event_cancelButton4ActionPerformed

    private void currencyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyComboBoxActionPerformed
        switch (currencyComboBox.getSelectedIndex()) {
            case FinancialFactors.USD:
                FinancialFactors.PREFERRED_CURRENCY = FinancialFactors.US_DOLLAR;
                break;
            case FinancialFactors.EGP:
                FinancialFactors.PREFERRED_CURRENCY = FinancialFactors.EGYPTIAN_POUND;
                break;
            case FinancialFactors.EUR:
                FinancialFactors.PREFERRED_CURRENCY = FinancialFactors.EURO;
                break;
            case FinancialFactors.STERLING:
                FinancialFactors.PREFERRED_CURRENCY = FinancialFactors.STERLING_POUND;
                break;
        }
    }//GEN-LAST:event_currencyComboBoxActionPerformed

    private void convertPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertPricesButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_convertPricesButtonActionPerformed

    private void currencyComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_currencyComboBoxPropertyChange

    }//GEN-LAST:event_currencyComboBoxPropertyChange

    public void navigateToPersonnelSettings(int tab) {
        mainTabbedPane.setSelectedIndex(2);
        personnelPane.setSelectedIndex(tab);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane adminInfoPane;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JButton cancelButton3;
    private javax.swing.JButton cancelButton4;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton changeUsernameButton;
    private javax.swing.JButton convertPricesButton;
    private javax.swing.JComboBox<String> currencyComboBox;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> dayComboBox1;
    private javax.swing.JPanel deliverersTab;
    private javax.swing.JSpinner deliveryFeesSpinner;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton editDeliveryFeesButton;
    private javax.swing.JButton editTaxesButton;
    private javax.swing.JScrollPane financialPane;
    private javax.swing.JPanel generalTab;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JComboBox<String> monthComboBox1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTabbedPane personnelPane;
    private javax.swing.JPanel pharmacistsTab;
    private javax.swing.JLabel promptLabel1;
    private javax.swing.JLabel promptLabel2;
    private javax.swing.JButton resetLoginCredentialsButton;
    private javax.swing.JSpinner taxSpinner;
    private javax.swing.JTextField usernameField;
    private javax.swing.JComboBox<String> yearComboBox1;
    // End of variables declaration//GEN-END:variables
}
