/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.adminspecific;

import controller.filehandling.DelivererFileHandler;
import controller.financial.FinancialFactors;
import controller.management.personnel.PersonnelHandler;
import model.operations.Operation;
import model.personnel.Deliverer;
import system.general.DataEntryChecker;
import view.optionpanes.CustomOptionPane;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.Calendar;

/**
 * @author Adham Mohamed Aly
 */
public class ManageDelivererFrame extends javax.swing.JFrame {

    public static Deliverer displayedDeliverer;
    private String tempVehicle = displayedDeliverer.getVehicle();
    private String tempVehicleType = displayedDeliverer.getVehicleType();
    private double tempSalary = displayedDeliverer.getSalary();

    /**
     * Creates new form ManagePharmacistFrame
     */
    public ManageDelivererFrame() {
        initComponents();
        customInitComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delivererExclusive = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        label1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        professionLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        label2 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        saveChangesButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        dobLabel = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        editVehicleButton = new javax.swing.JButton();
        salaryConfirmButton = new javax.swing.JButton();
        editSalaryButton = new javax.swing.JButton();
        salaryCancelButton = new javax.swing.JButton();
        vehicleCancelButton = new javax.swing.JButton();
        label9 = new javax.swing.JLabel();
        vehicleTypeComboBox = new javax.swing.JComboBox<>();
        vehicleField = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        javax.swing.GroupLayout delivererExclusiveLayout = new javax.swing.GroupLayout(delivererExclusive);
        delivererExclusive.setLayout(delivererExclusiveLayout);
        delivererExclusiveLayout.setHorizontalGroup(
            delivererExclusiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        delivererExclusiveLayout.setVerticalGroup(
            delivererExclusiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage deliverer \"" + displayedDeliverer.getName() + "\" #" + displayedDeliverer.getId());
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/logo/cover.png"))); // NOI18N
        logo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(logo)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo))
        );

        label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label1.setText("NAME:");

        nameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nameLabel.setText("<name>");

        label3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label3.setText("Profession :");

        professionLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        professionLabel.setText("Deliverer");

        label2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label2.setText("ID #");

        idLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        idLabel.setText("<id>");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jLabel1.setOpaque(true);

        saveChangesButton.setBackground(new java.awt.Color(230, 230, 230));
        saveChangesButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        saveChangesButton.setText("Save Changes");
        saveChangesButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        saveChangesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveChangesButton.setEnabled(false);
        saveChangesButton.setFocusPainted(false);
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(230, 230, 230));
        deleteButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        deleteButton.setText("Delete Deliverer");
        deleteButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        dobLabel.setText("<dob>");

        label4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label4.setText("Date of Birth");

        editVehicleButton.setText("Edit Vehicle");
        editVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVehicleButtonActionPerformed(evt);
            }
        });

        salaryConfirmButton.setBackground(new java.awt.Color(51, 204, 0));
        salaryConfirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/tick-icon-2.png"))); // NOI18N
        salaryConfirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryConfirmButton.setFocusable(false);
        salaryConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryConfirmButtonActionPerformed(evt);
            }
        });

        editSalaryButton.setText("Edit");
        editSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSalaryButtonActionPerformed(evt);
            }
        });

        salaryCancelButton.setBackground(new java.awt.Color(255, 51, 51));
        salaryCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Very-Basic-Cancel-icon.png"))); // NOI18N
        salaryCancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryCancelButton.setFocusable(false);
        salaryCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryCancelButtonActionPerformed(evt);
            }
        });

        vehicleCancelButton.setBackground(new java.awt.Color(255, 51, 51));
        vehicleCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Very-Basic-Cancel-icon.png"))); // NOI18N
        vehicleCancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vehicleCancelButton.setFocusable(false);
        vehicleCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleCancelButtonActionPerformed(evt);
            }
        });

        label9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label9.setText("Vehicle :");

        vehicleTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bicycle", "Motorcycle", "Car" }));
        vehicleTypeComboBox.setEnabled(false);
        vehicleTypeComboBox.setFocusable(false);
        vehicleTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleTypeComboBoxActionPerformed(evt);
            }
        });

        vehicleField.setEditable(false);
        vehicleField.setText("<vehicle>");

        label7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label7.setText("Salary : " + FinancialFactors.PREFERRED_CURRENCY);

        salaryField.setEditable(false);
        salaryField.setText("<salary>");
        salaryField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salaryFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editVehicleButton)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vehicleField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vehicleCancelButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(professionLabel))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dobLabel))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salaryCancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salaryConfirmButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editSalaryButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(label1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(professionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobLabel))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salaryField)
                                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editSalaryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicleCancelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(label9)
                                        .addComponent(vehicleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editVehicleButton)
                                .addGap(122, 122, 122))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salaryConfirmButton)
                                    .addComponent(salaryCancelButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))))
        );

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void customInitComponents() {
        nameLabel.setText(displayedDeliverer.getName());
        idLabel.setText(String.valueOf(displayedDeliverer.getId()));
        dobLabel.setText(displayedDeliverer.getBirthDate().get(Calendar.DAY_OF_MONTH)
                + " / " + (displayedDeliverer.getBirthDate().get(Calendar.MONTH) + 1)
                + " / " + displayedDeliverer.getBirthDate().get(Calendar.YEAR));
        salaryField.setText(String.format("%.2f", displayedDeliverer.getSalary()));
        vehicleField.setText(displayedDeliverer.getVehicle());
        vehicleTypeComboBox.setSelectedItem(displayedDeliverer.getVehicleType());

        salaryCancelButton.setVisible(false);
        salaryConfirmButton.setVisible(false);
        vehicleCancelButton.setVisible(false);

        DefaultListModel<Operation> listModel = new DefaultListModel<>();
    }

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        displayedDeliverer.setVehicle(tempVehicle);
        displayedDeliverer.setSalary(tempSalary);
        displayedDeliverer.setVehicleType(tempVehicleType);

        new DelivererFileHandler().saveToFile();
        saveChangesButton.setEnabled(false);
        CustomOptionPane.showMessageDialog("Changes saved", "Success");
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int choice = JOptionPane.showConfirmDialog(null,
                "Are you sure you wish to completely remove\n\n     \"" + displayedDeliverer.getName() +
                        "\"\n\nfrom the system ?", "Permanently delete deliverer", JOptionPane.YES_NO_OPTION);

        if (choice == 0) {
            Deliverer.deliverers.remove(displayedDeliverer.getId() - PersonnelHandler.DELIVERER_BASE_ID);
            new DelivererFileHandler().saveToFile();
            AdminHome adminHome = new AdminHome();
            adminHome.navigateTo(AdminHome.PERSONNEL_TAB);
            adminHome.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void salaryCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryCancelButtonActionPerformed
        salaryField.setEditable(false);
        salaryField.setText(String.format("%.2f", tempSalary));
        salaryField.transferFocus();
        salaryCancelButton.setVisible(false);
        salaryConfirmButton.setVisible(false);
        editSalaryButton.setVisible(true);
    }//GEN-LAST:event_salaryCancelButtonActionPerformed

    private void vehicleCancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_vehicleCancelButtonActionPerformed
        vehicleField.setEditable(false);
        vehicleField.transferFocus();
        vehicleField.setText(tempVehicle);
        vehicleCancelButton.setVisible(false);
        editVehicleButton.setText("Edit Vehicle");
    }//GEN-LAST:event_vehicleCancelButtonActionPerformed

    private void editVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVehicleButtonActionPerformed
        if (!vehicleField.isEditable()) {
            editVehicleButton.setText("Apply");
            vehicleField.grabFocus();
        } else {
            String input = vehicleField.getText();
            if (!input.equals(tempVehicle)) {
                String process = input.equals(displayedDeliverer.getVehicle()) ?
                        "reset" : "changed successfully\nDon't forget to save your changes!";
                CustomOptionPane.showMessageDialog("Deliverer vehicle has been " + process, "Success");
                tempVehicle = input;
                saveChangesButton.setEnabled(!tempVehicle.equals(displayedDeliverer.getVehicle()));
            }
            editVehicleButton.setText("Edit Vehicle");
        }
        vehicleField.setEditable(!vehicleField.isEditable());
        vehicleTypeComboBox.setEnabled(!vehicleTypeComboBox.isEnabled());
        vehicleCancelButton.setVisible(vehicleField.isEditable());
    }//GEN-LAST:event_editVehicleButtonActionPerformed

    private void vehicleTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleTypeComboBoxActionPerformed
        tempVehicleType = (String) vehicleTypeComboBox.getSelectedItem();
        saveChangesButton.setEnabled(!tempVehicleType.equals(displayedDeliverer.getVehicleType()));
    }//GEN-LAST:event_vehicleTypeComboBoxActionPerformed

    private void editSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSalaryButtonActionPerformed
        salaryField.setEditable(true);
        salaryField.grabFocus();
        salaryCancelButton.setVisible(true);
        salaryConfirmButton.setVisible(true);
        editSalaryButton.setVisible(false);
    }//GEN-LAST:event_editSalaryButtonActionPerformed

    private void salaryConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryConfirmButtonActionPerformed
        double newSalary = Double.parseDouble(salaryField.getText());
        if (newSalary != tempSalary) {
            String word = newSalary > tempSalary ? "Raise" : "Cut";
            int choice = JOptionPane.showConfirmDialog(null,
                    word + " " + displayedDeliverer.getName() + "'s salary?" +
                            "\n\n   " + String.format("%.2f", tempSalary) + " ==> "
                            + String.format("%.2f", newSalary), "", JOptionPane.YES_NO_OPTION);

            if (choice == 0) {
                salaryField.setText(String.format("%.2f", newSalary));
                saveChangesButton.setEnabled(!(
                        String.format("%.2f", newSalary).equals(String.format("%.2f", displayedDeliverer.getSalary()))));
                tempSalary = newSalary;
            } else salaryField.setText(String.format("%.2f", tempSalary));
        }
        salaryField.setEditable(false);
        salaryField.transferFocus();
        salaryCancelButton.setVisible(false);
        salaryConfirmButton.setVisible(false);
        editSalaryButton.setVisible(true);
    }//GEN-LAST:event_salaryConfirmButtonActionPerformed

    private void salaryFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryFieldKeyReleased
        salaryField.setText(DataEntryChecker.fixDoubleInput(salaryField.getText()));
    }//GEN-LAST:event_salaryFieldKeyReleased

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        AdminHome adminHome = new AdminHome();
        adminHome.navigateTo(AdminHome.PERSONNEL_TAB);
        this.dispose();
        adminHome.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDelivererFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDelivererFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDelivererFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDelivererFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDelivererFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel delivererExclusive;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JButton editSalaryButton;
    private javax.swing.JButton editVehicleButton;
    private javax.swing.JPanel header;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel professionLabel;
    private javax.swing.JButton salaryCancelButton;
    private javax.swing.JButton salaryConfirmButton;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JButton vehicleCancelButton;
    private javax.swing.JTextField vehicleField;
    private javax.swing.JComboBox<String> vehicleTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
