/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.adminspecific;

import controller.filehandling.PharmacistFileHandler;
import controller.financial.FinancialFactors;
import controller.management.personnel.PersonnelHandler;
import model.operations.Operation;
import model.personnel.Pharmacist;
import system.general.DataEntryChecker;
import view.components.OperationsRenderer;
import view.optionpanes.CustomOptionPane;

import javax.swing.*;
import java.awt.*;
import java.util.Calendar;

/**
 * @author Adham Mohamed Aly
 */
public class ManagePharmacistFrame extends javax.swing.JFrame {

    public static Pharmacist displayedPharmacist;
    char defaultEchoChar;
    private String tempPassword = displayedPharmacist.getPassword();
    private double tempSalary = displayedPharmacist.getSalary();
    private boolean tempInventoryAccessGranted = displayedPharmacist.hasInventoryAccess();

    /**
     * Creates new form ManagePharmacistFrame
     */
    public ManagePharmacistFrame() {
        initComponents();
        defaultEchoChar = passwordField.getEchoChar();
        customInitComponents();

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        operationList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        professionLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        label2 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        assignAsManagerButton = new javax.swing.JButton();
        saveChangesButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        dobLabel = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        salaryCancelButton = new javax.swing.JButton();
        inventoryAccessCheckBox = new javax.swing.JCheckBox();
        changePasswordButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        passwordCancelButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        salaryConfirmButton = new javax.swing.JButton();
        editSalaryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage pharmacist \"" + displayedPharmacist.getName() + "\" #" + displayedPharmacist.getId());
        setMinimumSize(new java.awt.Dimension(853, 814));
        setResizable(false);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/logo/cover.png"))); // NOI18N
        logo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        backButton.setText("Back");
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(126, 126, 126)
                                .addComponent(backButton)
                                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(backButton)
                                        .addComponent(logo)))
        );

        label7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label7.setText("Salary : " + FinancialFactors.PREFERRED_CURRENCY);

        operationList.setBackground(new java.awt.Color(204, 204, 204));
        operationList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        operationList.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        operationList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        operationList.setCellRenderer(new OperationsRenderer());
        operationList.setFocusable(false);
        operationList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operationListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(operationList);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Operations handled:");

        label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label1.setText("NAME:");

        nameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nameLabel.setText("<name>");

        label3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label3.setText("Profession :");

        professionLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        professionLabel.setText("Pharmacist");

        label2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label2.setText("ID #");

        idLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        idLabel.setText("<id>");

        salaryField.setEditable(false);
        salaryField.setText("<salary>");
        salaryField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salaryFieldKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jLabel1.setOpaque(true);

        assignAsManagerButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        assignAsManagerButton.setText("Assign as manager");
        assignAsManagerButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        assignAsManagerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assignAsManagerButton.setEnabled(false);
        assignAsManagerButton.setFocusPainted(false);
        assignAsManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignAsManagerButtonActionPerformed(evt);
            }
        });

        saveChangesButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        saveChangesButton.setText("Save Changes");
        saveChangesButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        saveChangesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveChangesButton.setEnabled(false);
        saveChangesButton.setFocusPainted(false);
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        deleteButton.setText("Delete Pharmacist");
        deleteButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 190, 190), 4, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        dobLabel.setText("<dob>");

        label4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label4.setText("Date of Birth");

        salaryCancelButton.setBackground(new java.awt.Color(255, 51, 51));
        salaryCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Very-Basic-Cancel-icon.png"))); // NOI18N
        salaryCancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryCancelButton.setFocusable(false);
        salaryCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryCancelButtonActionPerformed(evt);
            }
        });

        inventoryAccessCheckBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        inventoryAccessCheckBox.setText("Has inventory access");
        inventoryAccessCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryAccessCheckBoxActionPerformed(evt);
            }
        });

        changePasswordButton.setText("Change Password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/hide-icon.png"))); // NOI18N
        jLabel9.setText("Show");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        passwordCancelButton.setBackground(new java.awt.Color(255, 51, 51));
        passwordCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/Very-Basic-Cancel-icon.png"))); // NOI18N
        passwordCancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passwordCancelButton.setFocusable(false);
        passwordCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCancelButtonActionPerformed(evt);
            }
        });

        passwordField.setEditable(false);
        passwordField.setText("<password>");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        salaryConfirmButton.setBackground(new java.awt.Color(51, 204, 0));
        salaryConfirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/tick-icon-2.png"))); // NOI18N
        salaryConfirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryConfirmButton.setFocusable(false);
        salaryConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryConfirmButtonActionPerformed(evt);
            }
        });

        editSalaryButton.setText("Edit");
        editSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSalaryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(assignAsManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(saveChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(label3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(professionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(350, 350, 350))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jSeparator1)
                                                                .addGap(179, 179, 179))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jSeparator2)
                                                                .addGap(179, 179, 179))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(label2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(451, 451, 451))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(label1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(408, 408, 408))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(443, 443, 443))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(label4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(376, 376, 376))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jSeparator3)
                                                                .addGap(179, 179, 179))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(label7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(salaryField)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(salaryCancelButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(salaryConfirmButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(editSalaryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(217, 217, 217))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passwordCancelButton)
                                                                .addGap(177, 177, 177))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(inventoryAccessCheckBox)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 12, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(nameLabel)
                                                        .addComponent(label1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(idLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(professionLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dobLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(editSalaryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(salaryConfirmButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(salaryCancelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(salaryField)
                                                        .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(passwordCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(passwordField))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(changePasswordButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inventoryAccessCheckBox)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(assignAsManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void customInitComponents() {
        nameLabel.setText(displayedPharmacist.getName());
        idLabel.setText(String.valueOf(displayedPharmacist.getId()));
        dobLabel.setText(displayedPharmacist.getBirthDate().get(Calendar.DAY_OF_MONTH)
                + " / " + (displayedPharmacist.getBirthDate().get(Calendar.MONTH) + 1)
                + " / " + displayedPharmacist.getBirthDate().get(Calendar.YEAR));
        salaryField.setText(String.format("%.2f", displayedPharmacist.getSalary()));
        passwordField.setText(displayedPharmacist.getPassword());
        inventoryAccessCheckBox.setSelected(tempInventoryAccessGranted);

        salaryCancelButton.setVisible(false);
        passwordCancelButton.setVisible(false);
        salaryConfirmButton.setVisible(false);

        DefaultListModel<Operation> listModel = new DefaultListModel<>();
        for (int opID : Operation.completedOperations.keySet()) {
            Operation op = Operation.completedOperations.get(opID);
            if (op.getPharmacist().getId() == displayedPharmacist.getId()
                    && op.getPharmacist().getName().equals(displayedPharmacist.getName())) {
                listModel.addElement(op);
            }
        }
        operationList.setModel(listModel);
    }

    private void assignAsManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignAsManagerButtonActionPerformed
        CustomOptionPane.showComingSoonDialog();
    }//GEN-LAST:event_assignAsManagerButtonActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        displayedPharmacist.setSalary(tempSalary);
        displayedPharmacist.setPassword(tempPassword);
        displayedPharmacist.setInventoryAccess(tempInventoryAccessGranted);

        new PharmacistFileHandler().saveToFile();
        saveChangesButton.setEnabled(false);
        CustomOptionPane.showMessageDialog("Changes saved", "Success");
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int choice = JOptionPane.showConfirmDialog(null,
                "Are you sure you wish to completely remove\n\n     \"" + displayedPharmacist.getName() +
                        "\"\n\nfrom the system ?", "Permanently delete pharmacist", JOptionPane.YES_NO_OPTION);

        if (choice == 0) {
            Pharmacist.pharmacists.remove(displayedPharmacist.getId() - PersonnelHandler.PHARMACIST_BASE_ID);
            new PharmacistFileHandler().saveToFile();
            AdminHome adminHome = new AdminHome();
            adminHome.navigateTo(AdminHome.PERSONNEL_TAB);
            adminHome.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        changePasswordFieldEchoChar();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void passwordCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCancelButtonActionPerformed
        passwordField.setEditable(false);
        passwordField.transferFocus();
        passwordField.setText(tempPassword);
        passwordCancelButton.setVisible(false);
        changePasswordButton.setText("Change Password");
        adjustPasswordFieldView();
    }//GEN-LAST:event_passwordCancelButtonActionPerformed

    private void salaryCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryCancelButtonActionPerformed
        salaryField.setEditable(false);
        salaryField.setText(String.format("%.2f", tempSalary));
        salaryField.transferFocus();
        salaryCancelButton.setVisible(false);
        salaryConfirmButton.setVisible(false);
        editSalaryButton.setVisible(true);
    }//GEN-LAST:event_salaryCancelButtonActionPerformed

    private void salaryConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryConfirmButtonActionPerformed
        double newSalary = Double.parseDouble(salaryField.getText());
        if (newSalary != tempSalary) {
            String word = newSalary > tempSalary ? "Raise" : "Cut";
            int choice = JOptionPane.showConfirmDialog(null,
                    word + " " + displayedPharmacist.getName() + "'s salary?" +
                            "\n\n   " + String.format("%.2f", tempSalary) + " ==> "
                            + String.format("%.2f", newSalary), "", JOptionPane.YES_NO_OPTION);

            if (choice == 0) {
                salaryField.setText(String.format("%.2f", newSalary));
                saveChangesButton.setEnabled(!(
                        String.format("%.2f", newSalary).equals(String.format("%.2f", displayedPharmacist.getSalary()))));
                tempSalary = newSalary;
            } else salaryField.setText(String.format("%.2f", tempSalary));
        }
        salaryField.setEditable(false);
        salaryField.transferFocus();
        salaryCancelButton.setVisible(false);
        salaryConfirmButton.setVisible(false);
        editSalaryButton.setVisible(true);
    }//GEN-LAST:event_salaryConfirmButtonActionPerformed

    private void editSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSalaryButtonActionPerformed
        salaryField.setEditable(true);
        salaryField.grabFocus();
        salaryCancelButton.setVisible(true);
        salaryConfirmButton.setVisible(true);
        editSalaryButton.setVisible(false);
    }//GEN-LAST:event_editSalaryButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        if (!passwordField.isEditable()) {
            changePasswordButton.setText("Apply");
            passwordField.grabFocus();
        } else {
            String input = passwordField.getText();
            if (!input.equals(tempPassword)) {
                String confirm = input.equals(displayedPharmacist.getPassword()) ? input : CustomOptionPane.showPasswordDialog();
                if (confirm != null && confirm.equals(input)) {
                    String process
                            = input.equals(displayedPharmacist.getPassword()) ?
                            "reset" : "changed successfully\nDon't forget to save your changes!";
                    CustomOptionPane.showMessageDialog("Pharmacist password has been " + process, "Success");
                    tempPassword = input;
                    saveChangesButton.setEnabled(!tempPassword.equals(displayedPharmacist.getPassword()));
                } else {
                    CustomOptionPane.showMessageDialog("Process Canceled");
                    passwordField.setText(tempPassword);
                }
            }
            changePasswordButton.setText("Change Password");
        }
        passwordField.setEditable(!passwordField.isEditable());
        passwordCancelButton.setVisible(passwordField.isEditable());
        adjustPasswordFieldView();
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void inventoryAccessCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryAccessCheckBoxActionPerformed
        tempInventoryAccessGranted = inventoryAccessCheckBox.isSelected();
        saveChangesButton.setEnabled(!(tempInventoryAccessGranted == displayedPharmacist.hasInventoryAccess()));
    }//GEN-LAST:event_inventoryAccessCheckBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        AdminHome adminHome = new AdminHome();
        adminHome.navigateTo(AdminHome.PERSONNEL_TAB);
        this.dispose();
        adminHome.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void operationListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operationListMouseClicked
        Operation selection = operationList.getSelectedValue();
        operationList.clearSelection();
        if (selection != null) {
            OperationDetailsFrame.displayedOp = selection;
        }
        new OperationDetailsFrame().setVisible(true);
    }//GEN-LAST:event_operationListMouseClicked

    private void salaryFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryFieldKeyReleased
        salaryField.setText(DataEntryChecker.fixDoubleInput(salaryField.getText()));
    }//GEN-LAST:event_salaryFieldKeyReleased

    private void changePasswordFieldEchoChar() {
        if (passwordField.getEchoChar() == (char) 0) {
            passwordField.setEchoChar(defaultEchoChar);
            jLabel9.setText("Show");
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/hide-icon.png")));
        } else {
            passwordField.setEchoChar((char) 0);
            jLabel9.setText("Hide");
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/eye-icon.png")));
        }
    }

    private void adjustPasswordFieldView() {
        passwordField.setEchoChar(defaultEchoChar);
        jLabel9.setText("Show");
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/icon/tools/hide-icon.png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePharmacistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePharmacistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePharmacistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePharmacistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePharmacistFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignAsManagerButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JButton editSalaryButton;
    private javax.swing.JPanel header;
    private javax.swing.JLabel idLabel;
    private javax.swing.JCheckBox inventoryAccessCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JList<Operation> operationList;
    private javax.swing.JButton passwordCancelButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel professionLabel;
    private javax.swing.JButton salaryCancelButton;
    private javax.swing.JButton salaryConfirmButton;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton saveChangesButton;
    // End of variables declaration//GEN-END:variables
}
