/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.general;

import controller.filehandling.DelivererFileHandler;
import controller.filehandling.OperationsFileHandler;
import controller.filehandling.PharmacistFileHandler;
import controller.filehandling.ProductFileHandler;
import system.general.DateAndTime;

import java.awt.*;

/**
 * @author Adham Mohamed Aly
 */
public class InitializationFrame extends javax.swing.JFrame {

    /**
     * Creates new form InitializationFrame
     */
    public InitializationFrame() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        this.setVisible(true);
        initProgram();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        progressLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 117, 119)), new javax.swing.border.LineBorder(new java.awt.Color(0, 170, 169), 2, true)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics_and_icons/logo/default.png"))); // NOI18N

        progressBar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        progressBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), null, null));
        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        progressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressLabel.setText("Initializing...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(progressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitializationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitializationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitializationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitializationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitializationFrame().setVisible(true);
            }
        });
    }

    private void initProgram() {
        /*==>  Load data from database  <==*/
        try {
            progressLabel.setText("Constructing Handlers...");
            PharmacistFileHandler pharmacistFileHandler = new PharmacistFileHandler();
            DelivererFileHandler delivererFileHandler = new DelivererFileHandler();
            ProductFileHandler productFileHandler = new ProductFileHandler();
            OperationsFileHandler operationsFileHandler = new OperationsFileHandler();
            for (int i = 0; i <= 10; i++) {
                progressBar.setValue(i);
                Thread.sleep(15);
            }

            progressLabel.setText("Loading Pharmacist Data...");
            pharmacistFileHandler.loadFromFile();  // Load pharmacist data
            for (int i = 10; i <= 20; i++) {
                progressBar.setValue(i);
                Thread.sleep(15);
            }

            progressLabel.setText("Loading Deliverer Data...");
            delivererFileHandler.loadFromFile();  // Load deliverer data
            for (int i = 20; i <= 30; i++) {
                progressBar.setValue(i);
                Thread.sleep(15);
            }

            progressLabel.setText("Loading Product Data...");
            productFileHandler.loadFromFile();  // Load product data
            for (int i = 30; i <= 40; i++) {
                progressBar.setValue(i);
                Thread.sleep(15);
            }

            progressLabel.setText("Preparing Logger...");
            operationsFileHandler.loadFromFile(); // Load completed operations data
            //TODO: Load Logger data
            for (int i = 40; i <= 50; i++) {
                progressBar.setValue(i);
                Thread.sleep(15);
            }

            progressLabel.setText("Setting Date & Time...");
            DateAndTime.setCurrentDate();
            for (int i = 50; i <= 60; i++) {
                progressBar.setValue(i);
                Thread.sleep(15);
            }

            progressLabel.setText("Almost There...");
            //TODO: Load preferred settings
            for (int i = 60; i <= 85; i++) {
                progressBar.setValue(i);
                Thread.sleep(15);
            }

            progressLabel.setText("Finalising...");
            //TODO
            for (int i = 85; i <= 100; i++) {
                progressBar.setValue(i);
                Thread.sleep(40);
            }
            progressLabel.setText("");
            progressBar.setStringPainted(true);
            progressBar.setString("All Done! :D");
            Thread.sleep(700);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        this.dispose();
        new HomePage().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    // End of variables declaration//GEN-END:variables
}
